// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehtvkfydzkwncevjdaql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVodHZrZnlkemt3bmNldmpkYXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NTMzMzIsImV4cCI6MjA2NzQyOTMzMn0.E6ehjttwTquFv8YDKBZs1fobR15GTLSHyx7d7Z6J3bY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});